name: Run EventHub Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init

      - name: Run Robot Framework tests
        env:
          TEST_USER_EMAIL: ${{ secrets.EVENTHUB_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.EVENTHUB_PASS }}
        run: |
          robot --outputdir results tests/

      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: robot-results
          path: results/
